# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mm',
            name='c',
            field=models.CharField(default='abc', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='mm',
            name='f',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mm',
            name='im',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mm',
            name='mc',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two')], default=2),
        ),
        migrations.AlterField(
            model_name='mm',
            name='mychoices',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mm',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('JR', 'Junior'), ('SR', 'Senior')], default='JR', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
